language: java
android:
  components:
   # The BuildTools version used by your project
    - build-tools-19.1.0

    # The SDK version used to compile your project
    - android-22

# Emulator Management: Create, Start and Wait
after_script:
 - echo 'after_build'
 
before_script:
 - echo 'start_build'
 # - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
 # - emulator -avd test -no-audio -no-window &
 # - android-wait-for-emulator
 # - adb shell input keyevent 82 &
